export const productCategoriesSeedList = [
  {
    name: 'Aperitivos',
    description: 'Pastéis, coxinhas, bolinhos, etc.',
    imageUrl: '/uploads/categories/aperitivos.webp',
  },
  {
    name: 'Bebidas',
    description: 'Refrigerantes, sucos, água, cerveja, etc.',
    imageUrl: '/uploads/categories/bebidas.jpg',
  },
  {
    name: 'Carnes',
    description: 'Carnes bovinas, suínas, aves, peixes, etc.',
    imageUrl: '/uploads/categories/carnes.webp',
  },
  { name: 'Doces', description: 'Sobremesas, bolos, tortas, etc.', imageUrl: '/uploads/categories/doces.jpg' },
  { name: 'Massas', description: 'Macarrão, lasanha, etc.', imageUrl: '/uploads/categories/massas.jpg' },
  { name: 'Pizzas', description: 'Pizzas de diversos sabores.', imageUrl: '/uploads/categories/pizzas.jpg' },
  { name: 'Saladas', description: 'Saladas de diversos tipos.', imageUrl: '/uploads/categories/saladas.jpg' },
  { name: 'Sopas', description: 'Sopas de diversos sabores.', imageUrl: '/uploads/categories/sopas.jpg' },
  { name: 'Sorvetes', description: 'Sorvetes de diversos sabores.', imageUrl: '/uploads/categories/sorvetes.jpg' },
  { name: 'Tortas', description: 'Tortas de diversos sabores.', imageUrl: '/uploads/categories/tortas.jpg' },
]

export const productIngredientsSeedList = [
  { name: 'Carne Moída', description: 'Carne moída.' },
  { name: 'Queijo', description: 'Queijo.' },
  { name: 'Frango', description: 'Frango.' },
  { name: 'Peixe', description: 'Peixe.' },
  { name: 'Batata Frita', description: 'Batata frita.' },
  { name: 'Bife', description: 'Bife.' },
  { name: 'Arroz', description: 'Arroz.' },
  { name: 'Cebola', description: 'Cebola.' },
  { name: 'Molho de Tomate', description: 'Molho de tomate.' },
  { name: 'Chocolate', description: 'Chocolate.' },
  { name: 'Morango', description: 'Morango.' },
  { name: 'Cenoura', description: 'Cenoura.' },
  { name: 'Lasanha', description: 'Lasanha.' },
  { name: 'Calabresa', description: 'Calabresa.' },
  { name: 'Salada', description: 'Salada.' },
  { name: 'Atum', description: 'Atum.' },
  { name: 'Legumes', description: 'Legumes.' },
  { name: 'Sopa', description: 'Sopa.' },
  { name: 'Sorvete', description: 'Sorvete.' },
  { name: 'Torta', description: 'Torta.' },
]

export const productSeedList = [
  {
    name: 'Pastel de Carne',
    description: 'Pastel de carne moída.',
    price: '5.00',
    imageUrl: '/uploads/products/pastel-de-carne.jpg',
    categoryId: 1,
    ingredientIds: [1],
  },
  {
    name: 'Pastel de Queijo',
    description: 'Pastel de queijo.',
    price: '5.00',
    imageUrl: '/uploads/products/pastel-de-queijo.jpg',
    categoryId: 1,
    ingredientIds: [2],
  },
  {
    name: 'Pastel de Frango',
    description: 'Pastel de frango.',
    price: '5.00',
    imageUrl: '/uploads/products/pastel-de-frango.jpg',
    categoryId: 1,
    ingredientIds: [3],
  },
  {
    name: 'Coca-Cola 2L',
    description: 'Refrigerante Coca-Cola 2L.',
    price: '10.00',
    imageUrl: '/uploads/products/coca-cola-2l.png',
    categoryId: 2,
    ingredientIds: [],
  },
  {
    name: 'Coca-Cola 600ml',
    description: 'Refrigerante Coca-Cola 350Ml.',
    price: '5.00',
    imageUrl: '/uploads/products/coca-cola-350ml.webp',
    categoryId: 2,
    ingredientIds: [],
  },
  {
    name: 'Agua Mineral 500ml',
    description: 'Água mineral 500ml.',
    price: '3.00',
    imageUrl: '/uploads/products/agua-mineral-500ml.jpg',
    categoryId: 2,
    ingredientIds: [],
  },
  {
    name: 'Peixe Frito',
    description: 'Peixe frito com batata frita.',
    price: '20.00',
    imageUrl: '/uploads/products/peixe-frito.webp',
    categoryId: 3,
    ingredientIds: [4, 5],
  },
  {
    name: 'Bife Acebolado',
    description: 'Bife acebolado com arroz e batata frita.',
    price: '20.00',
    imageUrl: '/uploads/products/bife-acebolado.jpg',
    categoryId: 3,
    ingredientIds: [6, 7, 8, 9],
  },
  {
    name: 'Bife à Parmegiana',
    description: 'Bife à parmegiana com arroz e batata frita.',
    price: '20.00',
    imageUrl: '/uploads/products/bife-a-parmegiana.jpg',
    categoryId: 3,
    ingredientIds: [6, 7, 8, 9],
  },
  {
    name: 'Bolo de Chocolate',
    description: 'Bolo de chocolate.',
    price: '10.00',
    imageUrl: '/uploads/products/bolo-de-chocolate.jpg',
    categoryId: 4,
    ingredientIds: [10],
  },
  {
    name: 'Bolo de Morango',
    description: 'Bolo de morango.',
    price: '10.00',
    imageUrl: '/uploads/products/bolo-de-morango.jpg',
    categoryId: 4,
    ingredientIds: [11],
  },
  {
    name: 'Bolo de Cenoura',
    description: 'Bolo de cenoura.',
    price: '10.00',
    imageUrl: '/uploads/products/bolo-de-cenoura.jpg',
    categoryId: 4,
    ingredientIds: [12],
  },
  {
    name: 'Lasanha de Frango',
    description: 'Lasanha de frango.',
    price: '20.00',
    imageUrl: '/uploads/products/lasanha-de-frango.jpg',
    categoryId: 5,
    ingredientIds: [13, 3],
  },
  {
    name: 'Lasanha de Carne',
    description: 'Lasanha de carne.',
    price: '20.00',
    imageUrl: '/uploads/products/lasanha-de-carne.jpg',
    categoryId: 5,
    ingredientIds: [1, 3],
  },
  {
    name: 'Lasanha de Queijo',
    description: 'Lasanha de queijo.',
    price: '20.00',
    imageUrl: '/uploads/products/lasanha-de-queijo.jpg',
    categoryId: 5,
    ingredientIds: [2, 3],
  },
  {
    name: 'Pizza de Calabresa',
    description: 'Pizza de calabresa.',
    price: '20.00',
    imageUrl: '/uploads/products/pizza-de-calabresa.jpg',
    categoryId: 6,
    ingredientIds: [14],
  },
  {
    name: 'Pizza de Frango',
    description: 'Pizza de frango.',
    price: '20.00',
    imageUrl: '/uploads/products/pizza-de-frango.jpg',
    categoryId: 6,
    ingredientIds: [3],
  },
  {
    name: 'Pizza de Queijo',
    description: 'Pizza de queijo.',
    price: '20.00',
    imageUrl: '/uploads/products/pizza-de-queijo.jpg',
    categoryId: 6,
    ingredientIds: [2],
  },
  {
    name: 'Salada de Frango',
    description: 'Salada de frango.',
    price: '10.00',
    imageUrl: '/uploads/products/salada-de-frango.jpg',
    categoryId: 7,
    ingredientIds: [3, 15],
  },
  {
    name: 'Salada de Atum',
    description: 'Salada de atum.',
    price: '10.00',
    imageUrl: '/uploads/products/salada-de-atum.jpg',
    categoryId: 7,
    ingredientIds: [16, 15],
  },
  {
    name: 'Salada de Queijo',
    description: 'Salada de queijo.',
    price: '10.00',
    imageUrl: '/uploads/products/salada-de-queijo.jpg',
    categoryId: 7,
    ingredientIds: [2, 15],
  },
  {
    name: 'Sopa de Frango',
    description: 'Sopa de frango.',
    price: '10.00',
    imageUrl: '/uploads/products/sopa-de-frango.jpg',
    categoryId: 8,
    ingredientIds: [3, 17],
  },
  {
    name: 'Sopa de Legumes',
    description: 'Sopa de legumes.',
    price: '10.00',
    imageUrl: '/uploads/products/sopa-de-legumes.jpg',
    categoryId: 8,
    ingredientIds: [18, 17],
  },
  {
    name: 'Sopa de Queijo',
    description: 'Sopa de queijo.',
    price: '10.00',
    imageUrl: '/uploads/products/sopa-de-queijo.jpg',
    categoryId: 8,
    ingredientIds: [2, 17],
  },
  {
    name: 'Sorvete de Chocolate',
    description: 'Sorvete de chocolate.',
    price: '5.00',
    imageUrl: '/uploads/products/sorvete-de-chocolate.jpg',
    categoryId: 9,
    ingredientIds: [10],
  },
  {
    name: 'Sorvete de Morango',
    description: 'Sorvete de morango.',
    price: '5.00',
    imageUrl: '/uploads/products/sorvete-de-morango.jpg',
    categoryId: 9,
    ingredientIds: [11],
  },
  {
    name: 'Sorvete de Creme',
    description: 'Sorvete de creme.',
    price: '5.00',
    imageUrl: '/uploads/products/sorvete-de-creme.jpg',
    categoryId: 9,
    ingredientIds: [],
  },
  {
    name: 'Torta de Chocolate',
    description: 'Torta de chocolate.',
    price: '10.00',
    imageUrl: '/uploads/products/torta-de-chocolate.jpg',
    categoryId: 10,
    ingredientIds: [10],
  },
  {
    name: 'Torta de Morango',
    description: 'Torta de morango.',
    price: '10.00',
    imageUrl: '/uploads/products/torta-de-morango.jpg',
    categoryId: 10,
    ingredientIds: [11],
  },
  {
    name: 'Torta de Cenoura',
    description: 'Torta de cenoura.',
    price: '10.00',
    imageUrl: '/uploads/products/torta-de-cenoura.jpg',
    categoryId: 10,
    ingredientIds: [12],
  },
]

export const tableSeedList = [
  {
    number: 1,
    isAvailable: true,
  },
  {
    number: 2,
    isAvailable: false,
  },
  {
    number: 3,
    isAvailable: false,
  },
]
